create table public.trocas_teams (
  code text primary key check (char_length(code) between 2 and 5),
  name_pt text not null,
  group_letter char(1) check (group_letter between 'A' and 'L'),
  sticker_count smallint not null check (sticker_count > 0),
  kind text not null check (kind in ('team','fwc','special')),
  display_order smallint not null
);

alter table public.trocas_teams enable row level security;

create policy "trocas_teams read all"
  on public.trocas_teams for select using (true);

insert into public.trocas_teams (code, name_pt, group_letter, sticker_count, kind, display_order) values
  ('FWC', 'FIFA World Cup History', null, 20, 'fwc',     0),
  ('MEX', 'México',                  'A',  20, 'team',    1),
  ('RSA', 'África do Sul',           'A',  20, 'team',    2),
  ('KOR', 'República da Coreia',     'A',  20, 'team',    3),
  ('CZE', 'Tchéquia',                'A',  20, 'team',    4),
  ('CAN', 'Canadá',                  'B',  20, 'team',    5),
  ('BIH', 'Bósnia',                  'B',  20, 'team',    6),
  ('QAT', 'Catar',                   'B',  20, 'team',    7),
  ('SUI', 'Suíça',                   'B',  20, 'team',    8),
  ('BRA', 'Brasil',                  'C',  20, 'team',    9),
  ('MAR', 'Marrocos',                'C',  20, 'team',   10),
  ('HAI', 'Haiti',                   'C',  20, 'team',   11),
  ('SCO', 'Escócia',                 'C',  20, 'team',   12),
  ('USA', 'Estados Unidos',          'D',  20, 'team',   13),
  ('PAR', 'Paraguai',                'D',  20, 'team',   14),
  ('AUS', 'Austrália',               'D',  20, 'team',   15),
  ('TUR', 'Turquia',                 'D',  20, 'team',   16),
  ('GER', 'Alemanha',                'E',  20, 'team',   17),
  ('CUW', 'Curaçau',                 'E',  20, 'team',   18),
  ('CIV', 'Costa do Marfim',         'E',  20, 'team',   19),
  ('ECU', 'Equador',                 'E',  20, 'team',   20),
  ('NED', 'Países Baixos',           'F',  20, 'team',   21),
  ('JPN', 'Japão',                   'F',  20, 'team',   22),
  ('SWE', 'Suécia',                  'F',  20, 'team',   23),
  ('TUN', 'Tunísia',                 'F',  20, 'team',   24),
  ('BEL', 'Bélgica',                 'G',  20, 'team',   25),
  ('EGY', 'Egito',                   'G',  20, 'team',   26),
  ('IRN', 'República Islâmica do Irã','G', 20, 'team',   27),
  ('NZL', 'Nova Zelândia',           'G',  20, 'team',   28),
  ('ESP', 'Espanha',                 'H',  20, 'team',   29),
  ('CPV', 'Cabo Verde',              'H',  20, 'team',   30),
  ('KSA', 'Arábia Saudita',          'H',  20, 'team',   31),
  ('URU', 'Uruguai',                 'H',  20, 'team',   32),
  ('FRA', 'França',                  'I',  20, 'team',   33),
  ('SEN', 'Senegal',                 'I',  20, 'team',   34),
  ('IRQ', 'Iraque',                  'I',  20, 'team',   35),
  ('NOR', 'Noruega',                 'I',  20, 'team',   36),
  ('ARG', 'Argentina',               'J',  20, 'team',   37),
  ('ALG', 'Argélia',                 'J',  20, 'team',   38),
  ('AUT', 'Áustria',                 'J',  20, 'team',   39),
  ('JOR', 'Jordânia',                'J',  20, 'team',   40),
  ('POR', 'Portugal',                'K',  20, 'team',   41),
  ('COD', 'RD Congo',                'K',  20, 'team',   42),
  ('UZB', 'Uzbequistão',             'K',  20, 'team',   43),
  ('COL', 'Colômbia',                'K',  20, 'team',   44),
  ('ENG', 'Inglaterra',              'L',  20, 'team',   45),
  ('CRO', 'Croácia',                 'L',  20, 'team',   46),
  ('GHA', 'Gana',                    'L',  20, 'team',   47),
  ('PAN', 'Panamá',                  'L',  20, 'team',   48),
  ('CC',  'Coca-Cola',               null, 14, 'special', 99);
